In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
def ABCD1(l1,l2,l3,r):
    m1 = np.array([[1,l1/2],[0,1]])
    m2 = np.array([[1,0],[-2/r,1]])
    m3 = np.array([[1,l3+2*l2],[0,1]])
    m4 = np.array([[1,0],[-2/r,1]])
    m5 = np.array([[1,l1/2],[0,1]])
    mul = np.matmul(m4,m5)
    mul = np.matmul(m3,mul)
    mul = np.matmul(m2,mul)
    mul= np.matmul(m1,mul)
    return mul
    

In [78]:
def ABCD2(l1,l2,l3,r):
    m1 = np.array([[1,l2+l3/2],[0,1]])
    m2 = np.array([[1,0],[-2/r,1]])
    m3 = np.array([[1,l1],[0,1]])
    m4 = np.array([[1,0],[-2/r,1]])
    m5 = np.array([[1,l2+l3/2],[0,1]])
    mul = np.matmul(m4,m5)
    mul = np.matmul(m3,mul)
    mul = np.matmul(m2,mul)
    mul= np.matmul(m1,mul)
    return mul    

In [50]:
def d(a,b,wl):
    return np.sqrt(wl*np.abs(b)/np.pi/np.sqrt(1-a**2))

In [79]:
# test params
l1 = 31
l2 = 47
l3 = 56
r = 30
wl = 5.47e-3

In [80]:
abcd1 = ABCD1(l1,l2,l3,r)
abcd2 = ABCD2(l1,l2,l3,r)

In [81]:
d1 = d(abcd1[0,0],abcd1[0,1],wl)
d2 = d(abcd2[0,0],abcd2[0,1],wl)

In [102]:
print(d1*1000,',',d2*10000, 'μm')


47.11205715096438 , 5160.867286411156 μm


In [103]:
# test params
l1 = 110
l2 = 135
l3 = 138
r = 100
wl = 1.087e-3

In [104]:
abcd1 = ABCD1(l1,l2,l3,r)
abcd2 = ABCD2(l1,l2,l3,r)

In [105]:
d1 = d(abcd1[0,0],abcd1[0,1],wl)
d2 = d(abcd2[0,0],abcd2[0,1],wl)

In [107]:
print(d1*1000,',',d2*1000, 'μm')


50.92296497077628 , 282.61098621882894 μm


In [83]:
d2

0.5160867286411156

In [43]:
a
ma1 = ABCD1(0.115,0.138,0.135,0.100)

In [73]:
ma1 = ABCD1(115,138,135,100)

In [74]:
ma1

array([[-0.067 , -8.0025],
       [ 0.1244, -0.067 ]])

In [44]:
ma1

array([[-6.7000e-02, -8.0025e-03],
       [ 1.2440e+02, -6.7000e-02]])

In [45]:
ma1[0,1]

-0.0080025

In [46]:
ma1[0,0]**2

0.0044890000000000225

In [77]:
d(ma1[0,0],ma1[0,1],5.26e-3)

0.04619886191392761

In [76]:
ma1 = ABCD1(31,47,56,30)

In [66]:
ma1

array([[-0.73333333, -0.86666667],
       [ 0.53333333, -0.73333333]])

In [49]:
m1 = np.array([[1,100/2],[0,1]])
m2 = np.array([[1,110/2],[0,1]])

In [14]:
np.dot(m1,m2)

array([[  1., 105.],
       [  0.,   1.]])

In [9]:
np.matmul(m1,m2)

array([[  1., 105.],
       [  0.,   1.]])